# Generated by Django 5.0.1 on 2024-02-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListaReproduccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ListaReproduccion.genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ListaReproduccion.usuario'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaReproduccion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lista_reproduccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaReproduccion.listareproduccion')),
            ],
        ),
    ]
