CREATE DATABASE bd_lista_guillermo;

--tabla usuario
CREATE TABLE USUARIO(
    NICKNAME VARCHAR(20),
    NOMBRE_APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL,
    PRIMARY KEY(NICKNAME)
);

--tabla genero
CREATE TABLE GENERO(

    ID INT AUTO_INCREMENT,
    DESCRICPCION VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);

--tabla cancion
CREATE TABLE CANCION(
    ID INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    AUTOR VARCHAR(100),
    NICKNAME VARCHAR(100)
    GENERO_ID INT,
    PRIMARY KEY(ID)
);

ALTER TABLE CANCION ADD CONSTRAINT fk_cancion_usuario
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

ALTER TABLE CANCION ADD CONSTRAINT fk_cancion_genero
FOREIGN KEy(GENERO_ID) REFERENCES GENERO(ID);

CREATE TABLE LISTA_REPRODUCCION(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    NICKNAME VARCHAR(20),
    PRIMARY KEY(ID)
);

ALTER TABLE LISTA_REPRODUCCION ADD CONSTRAINT fk_lista_usuario
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

--TABLA LISTA CANCION
CREATE TABLE LISTA_CANCION(
    LISTA_ID INT,
    CANCION_ID INT,
);

ALTER TABLE LISTA_CANCION ADD CONSTRAINT pk_lista_cancion
PRIMARY KEY(LISTA_ID, CANCION_ID);

ALTER TABLE LISTA_CANCION ADD CONSTRAINT fk_listac_listar
FOREIGN KEy(LISTA_ID) REFERENCES LISTA_REPRODUCCION(ID);

ALTER TABLE LISTA_CANCION ADD CONSTRAINT fk_listac_cancion
FOREIGN KEY(CANCION_ID) REFERENCES CANCION(ID);

-- INSERTAR USUARIO
INSERT INTO USUARIO VALUES('moios', 'Moi Avalos', 'moios@gmail.com', '12345');
INSERT INTO USUARIO VALUES('pepe', 'Pedro Perez', 'pepe@gmail.com');

insert into GENERO values(default, "ROCK PARAGUAYO"); -- 1
insert into GENERO values(default, "PUNK ROCK PARAGUAYO");
insert into genero(descripcion) values("TRAP");

insert into CANCION
values (default, "Tanto y Nada", "FLOU", "moios",1);
insert into CANCION
values (default, "Aqui estoy", "Area 69", "pepe", 
(select id from genero where DESCRICPCION = "PUNK ROCK PARAGUAYO"));


UPDATE USUARIO SET NOMBRE_APELLIDO = 'MOISES AVALOS'
WHERE NICKNAME LIKE 'moios';

UPDATE USUARIO
set PASSWORD = "11111" WHERE NICKNAME = "pepe";


SELECT * FROM USUARIO;
SELECT email FROM USUARIO WHERE NICKNAME LIKE 'moios';

SELECT C.NOMBRE, C.AUTOR, G.DESCIPCION FROM CANCION C JOIN GENERO
ON C.GENERO_ID = G.ID
WHERE C.NICKNAME LIKE 'moios';



DELETE FROM USUARIO
WHERE NICKNAME = 'pepe';


